added some packages, services and people
Meteor-Community-Packages/awesome-meteor pull request #2
Opened 2023-09-24 20:09 UTC by guncebektas

add: some packages, services and people
feat: index

2023-09-25 22:54 UTC, guncebektas commented
I mean this one @jankapunkt

2023-09-27 06:27 UTC, jankapunkt commented
```shell
  readme.md:7:1
  ✖    1:1    Git repository must be at least 30 days old                   remark-lint:awesome-git-repo-age
  ✖    7:1    Main heading must be in title case                            remark-lint:awesome-heading
  ✖   30:1    ToC item "News" link "#News" not found                        remark-lint:awesome-toc
  ✖  106:140  Text "NodeJS" should be written as "Node.js"                  remark-lint:awesome-spell-check
  ✖  112:53   List item link and description must be separated with a dash  remark-lint:awesome-list-item
  ✖  116:68   List item description must end with proper punctuation        remark-lint:awesome-list-item
  ✖  118:77   List item description must end with proper punctuation        remark-lint:awesome-list-item
  ✖  125:4    Text "Youtube" should be written as "YouTube"                 remark-lint:awesome-spell-check
  ✖  125:51   Text "Youtube" should be written as "YouTube"                 remark-lint:awesome-spell-check
```

@StorytellerCZ can we disable or ignore rule 1?
@guncebektas can you fix the other lint issues?

2023-09-27 07:07 UTC, jankapunkt requested changes

2023-09-27 07:07 UTC, jankapunkt commented on readme.md
> +  <img src="https://github.com/guncebektas/awesome-meteor/blob/main/awesome-meteor.jpg" width="200"/>
This should be `https://github.com/Meteor-Community-Packages/awesome-meteor/blob/main/awesome-meteor.jpg`

2023-09-27 07:26 UTC, jankapunkt approved these changes

2023-09-27 07:27 UTC, jankapunkt commented
Approved, the one CI check fails due to deprecated deps in the ci config (related PR: #3). @StorytellerCZ can be merged from my end

2023-09-27 07:31 UTC, StorytellerCZ requested changes

2023-09-27 07:31 UTC, StorytellerCZ commented on readme.md
> +# Awesome Meteor [![Awesome](https://awesome.re/badge.svg)](https://awesome.re) [![lint](https://github.com/Meteor-Community-Packages/awesome-meteor/actions/workflows/lint.yaml/badge.svg)](https://gi
It should be Meteor.js

2023-09-27 07:31 UTC, StorytellerCZ commented on readme.md
> +- [Meteor Dispatched - Weekly News Podcast](https://www.youtube.com/@meteorjscommunity/podcasts)
Why is every word capitalized? It is not name of business or anything else.

2023-09-27 07:31 UTC, StorytellerCZ commented
Merging, but will fix the grammar issue in commit later.

2023-09-27 07:32 UTC, merged

2023-09-27 07:33 UTC, guncebektas commented on readme.md
> +# Awesome Meteor [![Awesome](https://awesome.re/badge.svg)](https://awesome.re) [![lint](https://github.com/Meteor-Community-Packages/awesome-meteor/actions/workflows/lint.yaml/badge.svg)](https://gi
linter warns about title case when .js

2023-09-27 07:36 UTC, guncebektas commented on readme.md
> +- [Meteor Dispatched - Weekly News Podcast](https://www.youtube.com/@meteorjscommunity/podcasts)
you are right. let's remove that weekly part?