minor updates
Meteor-Community-Packages/awesome-meteor pull request #5
Opened 2023-10-01 15:20 UTC by guncebektas

2023-10-02 05:59 UTC, jankapunkt requested changes

2023-10-02 05:59 UTC, jankapunkt commented on readme.md
> +Awesome packages, articles, tips and people all around Meteor
It should remain Meteor.js as this is the only way to get everything SEO compatible (otherwise people often end up with Astronomy-related content).

If linter nags then we need to adjust this for an exception

2023-10-02 05:59 UTC, jankapunkt commented on readme.md
> +<a href="https://www.meteor.com" target="_blank" rel="noopener noreferrer">Meteor</a> is an open source platform for building Web, Mobile, and Desktop applications.
Same here

2023-10-02 05:59 UTC, jankapunkt commented on readme.md
> +- [Meteor 3 PR](https://github.com/meteor/meteor/pull/12359) - Development of the next generation of Meteor.
Same here

2023-10-02 05:59 UTC, jankapunkt commented on readme.md
> +  - [ostrio:logger](https://packosphere.com/ostrio/logger) - Logger driver for Meteor with different adapters.
Same here

2023-10-02 05:59 UTC, jankapunkt commented on readme.md
> +Awesome packages, articles, tips and people all around Meteor
cc @StorytellerCZ

2023-10-02 06:14 UTC, StorytellerCZ commented on readme.md
> +Awesome packages, articles, tips and people all around Meteor
Yes

2023-10-02 06:16 UTC, StorytellerCZ requested changes
Reverse changes on existing content. Once that is done we can merge.

2023-10-02 06:16 UTC, guncebektas commented on readme.md
> +Awesome packages, articles, tips and people all around Meteor
It only negs on title. Thus, I just want to be consistent. If we prefer .js, I will update them all.

2023-10-03 09:04 UTC, guncebektas commented on readme.md
> +  - [ostrio:logger](https://packosphere.com/ostrio/logger) - Logger driver for Meteor with different adapters.
I removed the `Meteor` word from some of the definitions

2023-10-03 09:06 UTC, guncebektas commented
hi again, I think there are some improvements that we can merge.

2023-10-03 11:51 UTC, StorytellerCZ approved these changes

2023-10-12 12:08 UTC, merged